[[headers]]
  for = "/*"
  [headers.values]
    Header-Name1 = "Valor global para todos los archivos"
    Header-Name2 = "Otro valor global"

[[headers]]
  for = "/fafi.html"
  [headers.values]
    Encabezado-Fafi = "Valor para la p치gina FAFI"

[[headers]]
  for = "/derecho.html"
  [headers.values]
    Encabezado-Derecho = "Valor para la p치gina DERECHO"
    [[headers]]

  for = "/economia.html"
  [headers.values]
    Encabezado-Derecho = "Valor para la p치gina DERECHO"

[[headers]]
  for = "/rectorado.html"
  [headers.values]
    Encabezado-Derecho = "Valor para la p치gina DERECHO"